@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.entity.boss.bar;

import twilightforest.util.annotation.FieldsAreNonnullByDefault;
import twilightforest.util.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;