org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=false

# Mod Info
mod_version=1.0.0-beta
mod_id=twilightforest
group_name=com.github.teamtwilight.twilightforest

# Minecraft + Fabric
minecraft_version=1.21.11
loader_version=0.18.4
fabric_api_version=0.141.3+1.21.11
yarn_mappings=1.21.11+build.4

# Optional deps (compileOnly unless noted)
beanification_version=1.5.97
jei_version=27.4.0.15
