org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=false

# Mod Info
mod_version=1.0.0
mod_id=twilightforest
group_name=com.github.teamtwilight.twilightforest

# Minecraft + Fabric
minecraft_version=26.1.2
loader_version=0.19.2
fabric_api_version=0.149.0+26.1.2

# Optional deps (compileOnly unless noted)
beanification_version=1.5.97
jei_version=29.5.0.24
