org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.configuration-cache=false

# Mod Info
mod_version=1.0.0-beta.2
api_version=1.0.0
mod_id=twilightforest
group_name=com.github.teamtwilight.twilightforest

# Minecraft + Fabric
minecraft_version=26.2
loader_version=0.19.3
fabric_api_version=0.153.0+26.2
tomlj_version=1.1.1
antlr_version=4.11.1

# Optional deps (compileOnly unless noted)
beanification_version=1.5.97
jei_version=30.2.0.18
jade_version=26.2.9+fabric
