@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.init;

import twilightforest.util.annotation.FieldsAreNonnullByDefault;
import twilightforest.util.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;