@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package twilightforest.entity.ai.goal;

import twilightforest.util.annotation.FieldsAreNonnullByDefault;
import twilightforest.util.annotation.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;